---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  api_key: SCOPUS_API_TOKEN
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  api_key_backup: SCOPUS_API_TOKEN
  SESSION_SECRET: SESSION_SECRET
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  AWS_REGION: AWS_REGION
  TREE_QUEUE_URL: TREE_QUEUE_URL
  QUEUE: Queue
  API_HOST: http://localhost:9090

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  api_key: SCOPUS_API_TOKEN
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku